package com.jiafang.model;
// Generated 2015-10-5 22:12:51 by Hibernate Tools 4.3.1.Final

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Transient;

/**
 * CategoryRelationship generated by hbm2java
 */
@Entity
@Table(name = "CategoryRelationship")
public class CategoryRelationship extends BaseTime implements java.io.Serializable {

	private int id;
	private Integer companyId;
	private Integer productId;
	private Integer categoryId;
	private String video;
	private String avatar;
	private Integer weight;
	
	private String categoryName;//类别名称

	public CategoryRelationship() {
	}

	public CategoryRelationship(int id) {
		this.id = id;
	}

	public CategoryRelationship(int id, Integer companyId, Integer productId, Integer categoryId, String video,
			String avatar) {
		this.id = id;
		this.companyId = companyId;
		this.productId = productId;
		this.categoryId = categoryId;
		this.video = video;
		this.avatar = avatar;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "company_id")
	public Integer getCompanyId() {
		return this.companyId;
	}

	public void setCompanyId(Integer companyId) {
		this.companyId = companyId;
	}

	@Column(name = "product_id")
	public Integer getProductId() {
		return this.productId;
	}

	public void setProductId(Integer productId) {
		this.productId = productId;
	}

	@Column(name = "category_id")
	public Integer getCategoryId() {
		return this.categoryId;
	}

	public void setCategoryId(Integer categoryId) {
		this.categoryId = categoryId;
	}

	@Column(name = "video", length = 45)
	public String getVideo() {
		return this.video;
	}

	public void setVideo(String video) {
		this.video = video;
	}

	@Column(name = "avatar", length = 45)
	public String getAvatar() {
		return this.avatar;
	}

	public void setAvatar(String avatar) {
		this.avatar = avatar;
	}
	
	@Column
	public Integer getWeight() {
		return weight;
	}

	public void setWeight(Integer weight) {
		this.weight = weight;
	}
	
	
	@Transient
	public String getCategoryName() {
		return categoryName;
	}
	
	public void setCategoryName(String categoryName) {
		this.categoryName = categoryName;
	}

}
