package com.jiafang.model;
// Generated 2015-10-5 22:12:51 by Hibernate Tools 4.3.1.Final

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;
import java.util.List;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Transient;

/**
 * Company generated by hbm2java
 */
@Entity
@Table(name = "Company")
public class Company extends BaseTime implements java.io.Serializable,Categoryable {

	private Integer id;
	private String name;
	private String avatar;
	private String tel;
	private String website;
	private String video;
	private Integer userId;
	private String brand;
	private String desp;
	private String culture;
	private String address;
	private Integer weight;

	private String province;
	private String city;
	private String area;
	
	private String joinProcess;//加盟流程
	private String joinCondition;//加盟条件
	private String joinSurport;//加盟支持
	
	private List<Pic> storePics;//门店展示
	
	private CategoryRelationship categoryShip;
	private List<CategoryRelationship> categoryShips;
	
	private List<Pic> pics;
	
	private List<Brand> brands;
	
	private Date picUpdateTime;

	private String wechatAccount;
	private String alipayAccount;
	
	public Company() {
	}

	public Company(String name, String avatar, String tel, String website, String video, Integer userId) {
		this.name = name;
		this.avatar = avatar;
		this.tel = tel;
		this.website = website;
		this.video = video;
		this.userId = userId;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "name", length = 45)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "avatar", length = 45)
	public String getAvatar() {
		return this.avatar;
	}

	public void setAvatar(String avatar) {
		this.avatar = avatar;
	}

	@Column(name = "tel", length = 128)
	public String getTel() {
		return this.tel;
	}

	public void setTel(String tel) {
		this.tel = tel;
	}

	@Column(name = "website", length = 45)
	public String getWebsite() {
		return this.website;
	}

	public void setWebsite(String website) {
		this.website = website;
	}

	@Column(name = "video", length = 45)
	public String getVideo() {
		return this.video;
	}

	public void setVideo(String video) {
		this.video = video;
	}

	@Column(name = "user_id")
	public Integer getUserId() {
		return this.userId;
	}

	public void setUserId(Integer userId) {
		this.userId = userId;
	}
	@Transient
	public List<Pic> getPics() {
		return pics;
	}

	public void setPics(List<Pic> pics) {
		this.pics = pics;
	}

	@Transient
	@Override
	public String getTargetType() {
		return "company";
	}

	@Override
	public void setTargetType(String t) {
	}

	@Column
	public String getCulture() {
		return culture;
	}

	public void setCulture(String culture) {
		this.culture = culture;
	}
	@Column
	public String getDesp() {
		return desp;
	}

	public void setDesp(String desp) {
		this.desp = desp;
	}
	
	@Column
	public String getAddress() {
		return address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	@Transient
	public List<CategoryRelationship> getCategoryShips() {
		return categoryShips;
	}

	public void setCategoryShips(List<CategoryRelationship> categoryShips) {
		this.categoryShips = categoryShips;
	}
	@Transient
	public CategoryRelationship getCategoryShip() {
		return categoryShip;
	}

	public void setCategoryShip(CategoryRelationship categoryShip) {
		this.categoryShip = categoryShip;
	}
	@Transient
	public List<Pic> getStorePics() {
		return storePics;
	}

	public void setStorePics(List<Pic> storePics) {
		this.storePics = storePics;
	}
	
	@Column(length=2048)
	public String getJoinProcess() {
		return joinProcess;
	}

	public void setJoinProcess(String joinProcess) {
		this.joinProcess = joinProcess;
	}
	@Column(length=2048)
	public String getJoinCondition() {
		return joinCondition;
	}

	public void setJoinCondition(String joinCondition) {
		this.joinCondition = joinCondition;
	}
	@Column(length=2048)
	public String getJoinSurport() {
		return joinSurport;
	}

	public void setJoinSurport(String joinSurport) {
		this.joinSurport = joinSurport;
	}

	@Transient
	public List<Brand> getBrands() {
		return brands;
	}

	public void setBrands(List<Brand> brands) {
		this.brands = brands;
	}

	@Transient
	public String getBrand() {
		return brand;
	}

	public void setBrand(String brand) {
		this.brand = brand;
	}

	@Column
	public Integer getWeight() {
		return weight;
	}

	public void setWeight(Integer weight) {
		this.weight = weight;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((id == null) ? 0 : id.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		Company other = (Company) obj;
		if (id == null) {
			if (other.id != null)
				return false;
		} else if (!id.equals(other.id))
			return false;
		return true;
	}
	@Column(columnDefinition="TIMESTAMP")
	public Date getPicUpdateTime() {
		return picUpdateTime;
	}

	public void setPicUpdateTime(Date picUpdateTime) {
		this.picUpdateTime = picUpdateTime;
	}

	public String getProvince() {
		return province;
	}

	public void setProvince(String province) {
		this.province = province;
	}

	public String getCity() {
		return city;
	}

	public void setCity(String city) {
		this.city = city;
	}

	public String getArea() {
		return area;
	}

	public void setArea(String area) {
		this.area = area;
	}

	public String getWechatAccount() {
		return wechatAccount;
	}

	public void setWechatAccount(String wechatAccount) {
		this.wechatAccount = wechatAccount;
	}

	public String getAlipayAccount() {
		return alipayAccount;
	}

	public void setAlipayAccount(String alipayAccount) {
		this.alipayAccount = alipayAccount;
	}
}
