package com.jiafang.model;
// Generated 2015-10-5 22:12:51 by Hibernate Tools 4.3.1.Final

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;
import java.util.List;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Transient;

/**
 * Product generated by hbm2java
 */
@Entity
@Table(name = "Product")
public class Product extends BaseTime implements java.io.Serializable,Categoryable {

	private Integer id;
	private String name;
	private String avatar;
	private String video;
	private Double price;
	private Double discountPrice;
	private Integer saleCount;
	private Integer count;
	private String description;
	private Integer companyId;
	private Integer brandId;
	private String brand;
	private String num;
	private Integer weight;
	
	private List<Pic> pics;
	private List<SubProduct> subProduct;
	private List<Param> params;
	private List<Pic> descPics;
	
	private CategoryRelationship categoryShip;
	private List<CategoryRelationship> categoryShips;

	private Integer showPlatform;//在哪个平台显示   0-公共   1-私有  2-所有
	
	public Product() {
	}

	public Product(String name, String avatar, String video, Double price, Double discountPrice, Integer saleCount,
			Integer count, String description, Integer companyId) {
		this.name = name;
		this.avatar = avatar;
		this.video = video;
		this.price = price;
		this.discountPrice = discountPrice;
		this.saleCount = saleCount;
		this.count = count;
		this.description = description;
		this.companyId = companyId;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "name", length = 45)
	public String getName() {
		//return StringUtil.decode(this.name);
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "avatar", length = 45)
	public String getAvatar() {
		return this.avatar;
	}

	public void setAvatar(String avatar) {
		this.avatar = avatar;
	}

	@Column(name = "video", length = 45)
	public String getVideo() {
		return this.video;
	}

	public void setVideo(String video) {
		this.video = video;
	}

	@Column(name = "price", precision = 22, scale = 0)
	public Double getPrice() {
		return this.price;
	}

	public void setPrice(Double price) {
		this.price = price;
	}

	@Column(name = "discountPrice", precision = 22, scale = 0)
	public Double getDiscountPrice() {
		return this.discountPrice;
	}

	public void setDiscountPrice(Double discountPrice) {
		this.discountPrice = discountPrice;
	}

	@Column(name = "saleCount")
	public Integer getSaleCount() {
		return this.saleCount;
	}

	public void setSaleCount(Integer saleCount) {
		this.saleCount = saleCount;
	}

	@Column(name = "count")
	public Integer getCount() {
		return this.count;
	}

	public void setCount(Integer count) {
		this.count = count;
	}

	@Column(name = "description", length = 512)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "company_id")
	public Integer getCompanyId() {
		return this.companyId;
	}

	public void setCompanyId(Integer companyId) {
		this.companyId = companyId;
	}
	@Transient
	public List<Pic> getPics() {
		return pics;
	}

	public void setPics(List<Pic> pics) {
		this.pics = pics;
	}
	@Transient
	public List<Param> getParams() {
		return params;
	}

	public void setParams(List<Param> params) {
		this.params = params;
	}

	@Transient
	@Override
	public String getTargetType() {
		return "product";
	}

	@Override
	public void setTargetType(String t) {
		
	}
	@Transient
	public String getBrand() {
		return brand;
	}

	public void setBrand(String brand) {
		this.brand = brand;
	}

	@Transient
	public List<Pic> getDescPics() {
		return descPics;
	}

	public void setDescPics(List<Pic> descPics) {
		this.descPics = descPics;
	}

	@Transient
	@Override
	public List<CategoryRelationship> getCategoryShips() {
		return categoryShips;
	}

	@Override
	public void setCategoryShips(List<CategoryRelationship> categoryShips) {
		this.categoryShips = categoryShips;
	}

	/**
	 * 货号
	 * @return
	 */
	@Column
	public String getNum() {
		return num;
	}

	public void setNum(String num) {
		this.num = num;
	}
	@Transient
	public CategoryRelationship getCategoryShip() {
		return categoryShip;
	}

	public void setCategoryShip(CategoryRelationship categoryShip) {
		this.categoryShip = categoryShip;
	}
	@Column
	public Integer getBrandId() {
		return brandId;
	}

	public void setBrandId(Integer brandId) {
		this.brandId = brandId;
	}

	@Transient
	public List<SubProduct> getSubProduct() {
		return subProduct;
	}

	public void setSubProduct(List<SubProduct> subProduct) {
		this.subProduct = subProduct;
	}

	public Integer getWeight() {
		return weight;
	}

	public void setWeight(Integer weight) {
		this.weight = weight;
	}

	@Column(columnDefinition="INT default 2")
	public Integer getShowPlatform() {
		return showPlatform;
	}

	public void setShowPlatform(Integer showPlatform) {
		this.showPlatform = showPlatform;
	}
}
